### ISSUE TITLE
Sample Portfolio Site

### ISSUE THREAD

**Issue by takashi1kun** [CouchCMS/Documentation#33]
**Page:** ` https://docs.couchcms.com/tutorials/portfolio-site.html `

[Describe the issue here]
![image](https://user-images.githubusercontent.com/16158418/113152084-0c77d000-9236-11eb-827d-cbdf77718788.png)
There is a weird blank space below the footer.

**Comment by takashi1kun** [comment]
Proposed solution:
css:
```css
body {
    min-height: 100vh;
    display: flex;
    flex-direction: column;
}
.footer {
    margin-top: auto;
}
```
